baseURL = "/"
languageCode = "en-us"
theme = "poison"
paginate = 10
pluralizelisttitles = false   # removes the automatically appended "s" on sidebar entries

# NOTE: If using Disqus as commenting engine, uncomment and configure this line
# disqusShortname = "yourDisqusShortname"

[params]
    brand = "Ahmed Imtiaz Ferdous"#"AIFerdous"                      # name of your site - appears in the sidebar
    #remote_brand_image = '/picture.jpg' # path to a remote file
    brand_image = "/images/picture.png"    # path to the image shown in the sidebar
    description = "" # Used as default meta description if not specified in front matter
    dark_mode = true                      # optional - defaults to false
    #favicon = "favicon.ico"             # path to favicon (defaults to favicon.png)

    front_page_content = ["about"] # Equivalent to the default value, add page bundle names to include them on the front page.

    # MENU PLACEHOLDER
    # Menu dict keys:
        # Name:         The name to display on the menu.
        # URL:          The directory relative to the content directory.
        # HasChildren:  If the directory's files should be listed.  Default is true.
        # Limit:        If the files should be listed, how many should be shown.
    menu = [
        #{Name = "About", URL = "/about/", HasChildren = false},
        #{Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
        {Name = "Resume", URL = "/resume/", HasChildren = false},
        {Name = "Posts", URL = "/posts/", HasChildren = false},
        {Name = "Works", URL = "/works/", HasChildren = false},
        {Name = "Gallery", URL = "/gallery/", HasChildren = false}
        
    ]

    # Links to your socials.  Comment or delete any you don't need/use. 
    #discord_url = "https://discord.com"
    email_url = "mailto:aiferdous12641@gmail.com"
    facebook_url = "https://facebook.com/aiferdous"
    #flickr_url = "https://flickr.com"
    github_url = "https://github.com/sheriffMelamine"
    #gitlab_url = "https://gitlab.com"
    instagram_url = "https://instagram.com/_ai_ferdous_"
    linkedin_url = "https://linkedin.com/in/ahmed-imtiaz-ferdous"
    #mastodon_url = "https://mastodon.social"
    #matrix_url = "https://matrix.org"
    telegram_url = "https://t.me/AIFerdous"
    #tryhackme_url = "https://tryhackme.com"
    #twitter_url = "'file:///home/aiferdous/Downloads/picture.jpg'"
    #xmpp_url = "https://xmpp.org"
    youtube_url = "https://youtube.com/@ahmedimtiaz4187"

    # NOTE: If you don't want to use RSS, comment or delete the following lines
    # Adds an RSS icon to the end of the socials which links to {{ .Site.BaseURL }}/index.xml
    #rss_icon = true
    # Which section the RSS icon links to, defaults to all content. See https://gohugo.io/templates/rss/#section-rss
    #rss_section = "posts"

    # Hex colors for your sidebar.
    moon_sun_background_color = "#515151"   # default is #515151
    moon_sun_color = "#FB3"                  # default is #FFF
    sidebar_a_color = "#FB3"                 # default is #FFF
    sidebar_bg_color = "#252525"            # default is #202020
    sidebar_h1_color = "#FB3"               # default is #FFF
    sidebar_img_border_color = "#515151"    # default is #515151
    sidebar_p_color = "#909090"             # default is #909090
    sidebar_socials_color = "#FB3"           # default is #FFF

    # Hex colors for your content in light mode.
    code_color = "#000"                     # default is #000
    code_background_color = "#E5E5E5"       # default is #E5E5E5
    code_block_color = "#FFF"               # default is #FFF
    code_block_background_color = "#272822" # default is #272822
    content_bg_color = "#CCC"            # default is #FAF9F6
    date_color = "#515151"                  # default is #515151
    link_color = "#A01703"                  # default is #268BD2
    list_color = "#4A4A4A"                  # default is #5A5A5A
    post_title_color = "#303030"            # default is #303030
    table_border_color = "#000"          # default is #E5E5E5
    table_stripe_color = "#BBB"          # default is #F9F9F9
    text_color = "#000"                     # default is #222

    # Hex colors for your content in dark mode
    code_color_dark = "#FFF"                        # default is #FFF
    code_background_color_dark = "#515151"          # default is #515151
    code_block_color_dark = "#FFF"                  # default is #FFF
    code_block_background_color_dark = "#272822"    # default is #272822
    content_bg_color_dark = "#121212"               # default is #121212
    date_color_dark = "#9A9A9A"                     # default is #9A9A9A
    link_color_dark = "#D28B26"                     # default is #268BD2
    list_color_dark = "#9D9D9D"                     # default is #9D9D9D
    post_title_color_dark = "#DBE2E9"               # default is #DBE2E9
    table_border_color_dark = "#515151"             # default is #515151
    table_stripe_color_dark = "#202020"             # default is #202020
    text_color_dark = "#EEE"                        # default is #EEE

    # NOTE: If using Remark42 as commenting engine, uncomment and configure these lines
    # remark42 = true
    # remark42_host = "https://yourhost.com"
    # remark42_site_id = "your_site_id"

    # NOTE: The following three params are optional and are used to create meta tags + enhance SEO.
    # og_image = ""                       # path to social icon - front matter: image takes precedent, then og_image, then brand_url
                                          # this is also used in the schema output as well. Image is resized to max 1200x630
                                          # For this to work though og_image and brand_url must be a path inside the assets directory
                                          # e.g. /assets/images/site/og-image.png becomes images/site/og-image.png
    # publisher_icon = ""                 # path to publisher icon - defaults to favicon, used in schema
[params.meta]
    favicon = false
[taxonomies]
    series = 'series'
    tags = 'tags'
